#!/bin/bash

# test internat/network connection by ping-ing google.com (default) 5 times
# on a 5 second repeat

# hide cursor and trap on EXIT to reset:
trap 'tput cnorm' EXIT  # reset cursor
tput civis  # hide cursor


# TODO: optional user defined ip address parameter with default value.
#       tests for valid user input

while :;
    do
        clear
        ping -c 5 8.8.8.8

        count=1
        while [ $count -ne 0 ];
            do
                printf ".....\r"
                sleep 1
                printf ".... \r"
                sleep 1
                printf "...  \r"
                sleep 1
                printf "..   \r"
                sleep 1
                printf ".    \r"
                sleep 1
                printf "     \r"
                sleep 1
                count=0
            done
    done
